### ISSUE TITLE
masking empty DataFrame

### ISSUE THREAD

**Issue by kdebrab** [pydata/pandas#10126]
In pandas 0.16.1, I get a ValueError when trying to mask an empty DataFrame:
```python
>>> import pandas as pd
>>> df = pd.DataFrame()
>>> df[df>0]
Traceback (most recent call last):

  File "<ipython-input-3-efe84c9ebabc>", line 1, in <module>
    df[df>0]

  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 1787, in __getitem__
    return self._getitem_frame(key)

  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 1859, in _getitem_frame
    raise ValueError('Must pass DataFrame with boolean values only')

ValueError: Must pass DataFrame with boolean values only
```
Using 'where' works as expected:
```python
>>> df.where(df>0)
Out[4]: 
Empty DataFrame
Columns: []
Index: []
```
Also, masking a Series works as expected:
```python
>>> ts = pd.Series()
>>> ts[ts>0]
Out[6]: Series([], dtype: float64)
```

**Comment by jreback** [comment]
This can be trivial fixed by adding [here](https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#L1858)
``if len(key) and not is_bool_dtype(key.value):``

**Comment by shoyer** [comment]
fixed by #10196

**Comment by zhaoguixu** [comment]
This issue seems not fixed completely. I still get the same error. I have looked up the code and found that ```_getitem_frame``` was not fixed yet.

**Comment by jreback** [comment]
how so? are u using 0.16.2 at least

**Comment by zhaoguixu** [comment]
Yes, I am using the latest version. I have checked code of the master branch. ```_getitem_frame```(<a href=https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#L2035>here</a>) was not fixed as ```_setitem_frame```.

**Comment by jreback** [comment]
I think you are right. must have slipped by somehow. can you open a new issues (and xref this one), which a copy-pastable example (you can use the above) one.

pull-requests are welcome as well.
